Modify use of assertTrue(A in B)
Developers should use assertIn(A, B) instead of assertTrue(A in B).

Because assertIn raise more meaningful errors:
      self.assertIn(3, [1, 2]
      >>> MismatchError: 3 not in [1, 2]
      self.assertTrue(3 in [1, 2])
      >>> AssertionError: False is not true

TrivialFix

Change-Id: I09f0a348afba8b475b00913172a4dc0ce56f47ad