Fix docs build unknown target name error
When do the "tox docs" or "make html" in docs directory below error
is thrown in the middle of building docs and there are two broken links
in html output:

ERROR: Unknown target name: "restructuretext".
ERROR: Unknown target name: "conf override".

Change-Id: Icf4bc1b1bfbbbf2b3c2912bddd34dd5371b20afc
Closes-bug: #1510580
(cherry picked from commit 5a325c079878927cb7e9730801481fb8417a056d)