Lower default backup_metadata_version to 1
Kilo cinder supports both version 1 and 2, however juno cinder only
supports version 1.  Running
tempest.api.volume.admin.test_volumes_backup against a juno cinder
installation w/ backup_metadata_version set to 2 results in the
following cinder-backup error being logged:

BackupOperationError: Metadata restore failed due to incompatible
                      version

Partial-bug: #1399386
Change-Id: I20852c5fb331d9cbd297ecbd60a2b57d4fa37266